### ISSUE TITLE
createFromCrontabLine not allowing uppercase for days of the week

### ISSUE THREAD

**Issue by TomLorenzi** [TiBeN/CrontabManager#13]
If your cron tab is like 

`15 20 * * Sat,Sun ls /var/www/INDB/bref #specMoncode` this do no work but

`15 20 * * sat,sun ls /var/www/INDB/bref #specMoncode` this do.

**Comment by TomLorenzi** [comment]
#14 Here is a fix

**Comment by TiBeN** [comment]
PR merged. Thanks
