### ISSUE TITLE
Error when persisting a job.

### ISSUE THREAD

**Issue by lordcoste** [TiBeN/CrontabManager#2]
Hi, when I try to persist a cronjob I get this error:

Error when trying to write crontab : '-' does not exist. usage: crontab file crontab [ -e | -l | -r ] -e (edit user's crontab) -l (list user's crontab) -r (delete user's crontab)

Any idea about the cause?

Thanks.

**Comment by TiBeN** [comment]
clean ticket: It does not affect others, have no time take a look.
