### ISSUE TITLE
Comment at the end of line.

### ISSUE THREAD

**Issue by Movax12** [TiBeN/CrontabManager#5]
I can't find much after searching, but it seems that having the comment at the end of line is not supported by standard cron. 
This website says it is bad: http://www.alleft.com/sysadmin/common-cron-mistakes/

Is it possible to put the comment above the command to be safe?

Edit: This example may be refferring to the lack of space before the comment. Do you know for sure that the comment at the end of the line is safe?

**Comment by TiBeN** [comment]
Hi, thanks for take time to write an issue.

As you said in your EDIT i think cron as nothing to do with it. I'm not a cron internals guru, but i think it simply delegates the interpretation of the command line to shell. 

It is perfectly ok (someone shoulds correct me if i'm wrong) to have comments prefixed with a "#" at the end of a shell command line. As stated on the [GNU Bash Reference Manual, comments section](https://www.gnu.org/software/bash/manual/bash.html#Comments), The "#" char must be in the beginning of a word. This is not the case on the example given on the blog article you mentioned, that's here the issue.

**Comment by Movax12** [comment]
Thanks for replying. I think it's okay the way you have it.
