### ISSUE TITLE
Chainable Cronjob parameters

### ISSUE THREAD

**Issue by Menelion** [TiBeN/CrontabManager#9]
As for now, different cronjob parameters are exposed as properties (`$minutes`, `$hours` and so on).  
What I propose is to implement getters and setters for those so you could write something like this (rewriting the example from Readme):

```php
$crontabJob = new CrontabJob();
$crontabJob->setMinutes(30)->setHours(23)->setDayOfMonth('*')->setMonths('*')->setDayOfWeek('*')->setTaskCommandLine('df >> /tmp/df.log')->setComments('Logging disk usage');
```

Seems a bit more concise, no? :)  
If you have nothing against it, I'd implement this and send a PR. Thanks!

**Comment by TiBeN** [comment]
Hi Menelion,
Implementing as fluent interface sounds like a good idea. 
Could be planned for a 2.0 version because of breaking changes. Don't miss to modify unit tests accordingly.
Thanks

**Comment by Menelion** [comment]
I'll try to implement it without breaking anything, just add this functionality).
